### ISSUE TITLE
Generate a "blank" Word Search

### ISSUE THREAD

**Issue by cvalleroy** [CreativeRailsProject/RailsWordSearchProject#2]
Generate a 20 by 20 array word search, filled with single '/' characters.

**Comment by cvalleroy** [comment]
Word search is able to be generated, complete with random letters and can place words inside the Word Search array. Sill needs to be able to link up to the Ruby/Rails script for the web server.

**Comment by hmc-cs-lhernandezcruz** [comment]
done
